/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgView;

import java.util.Date;
import pkgController.NewInvoiceHeaderController;
import pkgModel.Entity.InvoiceHeader;

/**
 *
 * @author lenovo
 */
public class FrmNewInvoice extends javax.swing.JFrame {

    public InvoiceHeader newInvoice = new InvoiceHeader();

    /**
     * Creates new form frmNewInvoice
     */
    public FrmNewInvoice() {
        controller = new NewInvoiceHeaderController(this);
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        clnInvoiceDate.setDate(new Date());
    }

    public FrmNewInvoice(int invNum) {
           controller = new NewInvoiceHeaderController(this);
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        lblInvoiceNumberValue.setText(invNum + "");
        clnInvoiceDate.setDate(new Date());
        newInvoice.setInvoiceNum(invNum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnSave.addActionListener(controller);
        btnCancel = new javax.swing.JButton();
        btnCancel.addActionListener(controller);
        lblInvoiceNumber = new javax.swing.JLabel();
        lblInvoiceDate = new javax.swing.JLabel();
        clnInvoiceDate = new com.toedter.calendar.JDateChooser();
        txtCustomerName = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        lblInvoiceNumberValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Invoice");

        btnSave.setText("Save");
        btnSave.setToolTipText("");

        btnCancel.setText("Cancel");

        lblInvoiceNumber.setText("Invoice Number");

        lblInvoiceDate.setText("Invoice Date:");

        lblCustomerName.setText("Customer Name:");

        lblInvoiceNumberValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInvoiceNumberValue.setText("----");
        lblInvoiceNumberValue.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInvoiceNumber)
                                .addGap(18, 18, 18)
                                .addComponent(lblInvoiceNumberValue)
                                .addGap(231, 231, 231))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCustomerName)
                                    .addComponent(lblInvoiceDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clnInvoiceDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInvoiceNumber)
                    .addComponent(lblInvoiceNumberValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clnInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInvoiceDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    public com.toedter.calendar.JDateChooser clnInvoiceDate;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblInvoiceDate;
    private javax.swing.JLabel lblInvoiceNumber;
    public javax.swing.JLabel lblInvoiceNumberValue;
    public javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables

    NewInvoiceHeaderController controller;
}
